import AnimCursor from "@/components/AnimCursor";
import Login from "@/components/Login/Login";
import React from "react";

export const metadata: Metadata = {
  title: "Donation Website | LogIn",
  description: "Generated by create next app",
};


const LoginPage = () => {
  return (
    <div>
      <AnimCursor />
   <Login/>
    </div>
  );
};

export default LoginPage;
