import AnimCursor from "@/components/AnimCursor";
import Signup from "@/components/Signup/Signup";
import React from "react";

export const metadata: Metadata = {
  title: "Donation Website | SignUp",
  description: "Generated by create next app",
};

const SignupPage = () => {
  return (
    <div className="border rounded-xl shadow-lg p-5 mt-52">
      <AnimCursor />
      <Signup />
    </div>
  );
};

export default SignupPage;
