import NavbarHome from "@/components/Shared/NavbarHome";


export const metadata: Metadata = {
  title: "Donation Website",
  description: "Generated by create next app",
};


const HomeLayout = ({ children }: { children: React.ReactNode }) => {
  
  return (
    <div>
      <NavbarHome />
      {children}
    </div>
  );
};

export default HomeLayout;
