import AnimCursor from "@/components/AnimCursor";
import HomeBanner from "@/components/HomePage/HomeBanner";
import HomePageCategory from "@/components/HomePage/HomePageCategory";
import HomePageSearch from "@/components/HomePage/HomePageSearch";
interface Metadata {
  title: string;
  description: string;
}

export const metadata: Metadata = {
  title: "Donation Website | Home",
  description: "Generated by create next app",
};

const HomePage = () => {
  return (
    <div className="cursor-auto mt-52">
      <AnimCursor />
      <HomePageSearch />
      <HomeBanner />
      <HomePageCategory/>
    </div>
  );
};

export default HomePage;
