import AnimCursor from "@/components/AnimCursor";
import HomeBanner from "@/components/HomePage/HomeBanner";
import HomePageSearch from "@/components/HomePage/HomePageSearch";

export const metadata: Metadata = {
  title: "Donation Website | Home",
  description: "Generated by create next app",
};

const HomePage = () => {
  return (
    <div className="cursor-auto">
      <AnimCursor />
      <HomePageSearch />
      <HomeBanner />
    </div>
  );
};

export default HomePage;
